Flask(betaa) - Copy (2)/webapp/web/models.py
from .. import db


activity = db.Table('place_activity', 
    db.Column('places_id', db.Integer, db.ForeignKey('places.id')), 
    db.Column('activity_id', db.Integer, db.ForeignKey('activity.id'))) 
              
activity_marker = db.Table('marker_activity',
    db.Column('markers_id', db.Integer, db.ForeignKey('markers.id')),
    db.Column('activity_id', db.Integer, db.ForeignKey('activity.id')))

class Places(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.String(255))
    latitude = db.Column(db.String(350))
    longitude = db.Column(db.String(255))
    region = db.Column(db.String(255))
    text = db.Column(db.String(255))
    activity = db.relationship(
        'Activity',
        secondary=activity,
        backref=db.backref('places', lazy='dynamic')
    )
    
    def __init__(self, title="", text="",latitude="", longitude=""):
        self.title = title
        self.text = text
        self.latitude=latitude
        self.longitude=longitude

    def __repr__(self):
        return "<Post '{}'>".format(self.title)

class Markers(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.String(255))
    text = db.Column(db.String())
    latitude = db.Column(db.String(255))
    longitude = db.Column(db.String(255)) 
    user_id = db.Column(db.Integer(), db.ForeignKey('user.id'))
    activity_marker = db.relationship(
        'Activity', 
        secondary=activity_marker, 
        backref=db.backref('markers', lazy='dynamic'))

    def __init__(self, title="", text="", latitude="", longitude=""):
        self.title = title
        self.text = text 
        self.latitude = latitude
        self.longitude = longitude


    def __repr__(self):
        return "<Post '{}'>".format(self.title)

class Activity(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.String(255))

    def __init__(self, title=""):
        self.title = title

    def __repr__(self):
        return "<Activity '{}'>".format(self.title)

Flask(betaa) - Copy (2)/webapp/__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from sqlalchemy import text
 

db = SQLAlchemy()
migrate=Migrate()

"""The create_app() function is the application factory, which takes as an argument the name of 
a configuration to use for the application. The configuration settings stored in one of the classes
defined in config.py can be imported directly into the application using the from_object() method
available in Flask’s app.config configuration object. The configuration object is selected
by name from the config dictionary. Once an application is created and configured,
the extensions can be initialized. Calling init_app() on the extensions that were created
earlier completes their initialization."""

def page_not_found(error):
    return render_template('404.html'), 404 

def create_app(object_name):
    """Flask application factory"""
    app = Flask(__name__, static_folder='/static')

    app.config.from_object(object_name)
    

    db.init_app(app)
    migrate.init_app(app, db)
    from .auth import create_module as google_create_module
    from .main import create_module as main_create_module
    from .web import create_module as web_create_module
    #from .web import creat
    with app.app_context():
     google_create_module(app)
     main_create_module(app)
     web_create_module(app)
    
    return app
    
   

Flask(betaa) - Copy (2)/webapp/main/__init__.py
def create_module(app, **kwargs):
    from .controllers import main_blueprint
    app.register_blueprint(main_blueprint)

Flask(betaa) - Copy (2)/webapp/main/controllers.py
from flask import Blueprint, redirect, url_for, render_template
from flask_login import (
    LoginManager,
    current_user,
    login_required,
    login_user,
    logout_user,
)

main_blueprint = Blueprint(
    'main',
    __name__,
    template_folder='../templates'
)


@main_blueprint.route('/')
def index(): 
    return render_template('home.html')

@main_blueprint.route('/login_with_google')
def login_with_google():
    return redirect(url_for('google.login'))


@main_blueprint.route('/welcome')
#@login_required
def welcome():
    return render_template('welcome.html')


Flask(betaa) - Copy (2)/webapp/web/__init__.py
import secrets

def create_module(app, **kwargs):
    secret_key = secrets.token_hex(16)
    app.secret_key = secret_key 
    from .controllers import app_blueprint

    app.register_blueprint(app_blueprint)

Flask(betaa) - Copy (2)/webapp/web/controllers.py
from sqlalchemy import desc, func
from flask import render_template, Blueprint, flash, redirect, url_for, current_app, render_template_string, request
from flask_login import login_required, current_user
from .models import db, Markers, Activity, Places
from ..auth.models import User
import folium 
from folium.plugins import Geocoder
from folium.map import Marker
from flask import jsonify
import json
import geopy
from geopy.geocoders import Nominatim

app_blueprint = Blueprint(
    'web',
    __name__,
    template_folder='./templates',
    #url_prefix="/main"
    )

@app_blueprint.route('/getmap')
def getMap():
    return redirect(url_for('web.mapView')) 

@app_blueprint.route('/googlemaps')
#def getMapView(): 
 #   return render_template('map.html')
 

@app_blueprint.route('/map')
@login_required
def mapView():
    users=User.query.all()
    map = folium.Map(width=800, height=600,location=[21.2820, 106.1975] , zoom_start=12)
    places = Places.query.all()
    for place in places:
        lat = place.latitude
        lon = place.longitude
        folium.Marker(
            location=[float(lat), float(lon)],
            popup = folium.Popup(
                html='<img src="https://res.cloudinary.com/dggvywzge/image/upload/v1684314331/cat_jwiq4j.jpg" width="100px" height="90px">',
            
            max_width=200,
            show=False,
            sticky=False,        
            lazy=True)
        ).add_to(map)
        

    iframe = map.get_root()._repr_html_()
    

    
    return render_template("mapTest.html", iframe=iframe, users=users)

@app_blueprint.route('/usermap/<int:user_id>', methods=['GET', 'POST'])
@login_required
def user_map(user_id):       

    return render_template('userMap.html', current_user=current_user)

@app_blueprint.route('/usermarkers', methods=['GET', 'POST']) 
@login_required
def get_markers():
    markers = Markers.query.filter_by(user_id=current_user.id).all()
    markers_data = []

    for marker in markers:
        # Extract the necessary attributes from the marker object
        marker_data = {
            'id': marker.id,
            'latitude': marker.latitude,
            'longitude': marker.longitude,
            # Add other attributes as needed
        }
        markers_data.append(marker_data)

    markers_json = json.dumps(markers_data)
    return markers_json

@app_blueprint.route('/new', methods=['GET','POST'])
@login_required
def create_new_marker():
    new_marker = Markers()
    new_marker.title = request.form['title']
    new_marker.text = request.form['text']
    new_marker.latitude= request.form.get('lat')
    new_marker.longitude = request.form.get('lon')
    new_marker.user_id = current_user.id
    try: 
      db.session.add(new_marker) 
      db.session.commit()
    except Exception as e:
      flash('Error adding your marker: %s' % str(e), 'error')
      print('error adding marker')
      db.session.rollback()
    else: 
      flash('Created marker successfully', "message")
      print(new_marker.latitude, new_marker.longitude)
      return redirect(url_for('.user_map', user_id=current_user.id))

@app_blueprint.route('/selectRegion')
@login_required
def render_map_by_region(region):
    if region == 'Bac Giang':
        map = folium.Map(width=800, height=600,location=[21.2820, 106.1975] , zoom_start=12)
    place01 = folium.Marker(
        location=[21.2820, 106.2072],
        popup = folium.Popup(
        html='<img src="https://res.cloudinary.com/dggvywzge/image/upload/v1684314331/cat_jwiq4j.jpg" width="100px" height="90px">',
        max_width=200,
        show=False,
        sticky=False,        
        lazy=True
    )).add_to(map)
    
@app_blueprint.route('/delete/<int:marker_id>', methods=['GET', 'POST'])
@login_required
def delete_marker(marker_id):
    marker_to_delete = Markers.query.filter_by(id=marker_id).first()
    if marker_to_delete is None: 
     print("Cannot delete selected marker")
     return "False"
    else:
     print(marker_to_delete)
     db.session.delete(marker_to_delete)
     db.session.commit()
     print("Deleted successfully")
     flash("Deleted") 
     return "True"
    
     



Flask(betaa) - Copy (2)/webapp/templates/base.html
<!--{% extends "bootstrap/base.html" %}

{% block title %}Flasky{% endblock %}

{% block head %}
{{ super() }}
<!link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}"-->
<!--{% endblock %}

{% block navbar %}
<div class="navbar">
    <a href = "#" class = "logo">DUONG</a>
    <nav>
        <ul class="navlink">
            <li><a href="#">Home</a></li>

        </ul>
         
    </nav>
    <a class = "btn" href="{{ url_for('main.login_with_google') }}"><button>Login</button></a> 
</div>
{% endblock %} -->

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>{% block title %}Blog{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
</head>
<body>
{% include 'navbar.html' %}
<div class="container">
    <div class="row row-lg-4">
        <div class="col">
            {% block head %}
            {% include 'head.html' %}
            {% endblock %}
        </div>
    </div>
    {% include 'messages.html' %}
    {% block body %}
    <div class="row">
        <div class="col-lg-9">
            {% block leftbody %}
            {% endblock %}
        </div>
        <div class="col-lg-3 rounded">
            {% block rightbody %}
            {% include 'rightbody.html' %}
            {% endblock %}
        </div>
    </div>
    {% endblock %}
    {% include 'footer.html' %}
</div>
</body>
{% block js %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>    </body>
</html>

Flask(betaa) - Copy (2)/webapp/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block navbar %}
        
    

    {% endblock %}
    
</body>
</html>

<a href="{{ url_for('main.login_with_google') }}">Bam vao bo may ne</a> 



Flask(betaa) - Copy (2)/webapp/templates/infobox.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Infobox</title>
</head>
<body>
    
</body>
</html>

Flask(betaa) - Copy (2)/webapp/templates/loginrequired.html
{% extends 'base.html' %}
<div id="login-requqest"> 
    <p>You need to login to continue</p>
    <p> Try </p><a href="{{ url_for('main.login_with_google') }}">Bam vao bo may ne</a> 
    </p>
</div>

Flask(betaa) - Copy (2)/webapp/templates/map.html
<!DOCTYPE html>
  <head>
    <title>Add Map</title>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAid8qgyZORO_4JdIviZleNJbCIBfs8mVI&callback=initMap"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <style>
      #map{
        height: 400px;
        width: 100%
      }
    </style>

    <!--link rel="stylesheet" type="text/css" href="./style.css" /-->
    <script> 
        
        function initMap(){
            map = new google.maps.Map(document.getElementById("map"), {
                center: {lat:21.027763, lng:105.83416},
                zoom: 8,
            })
        }

    </script>

  </head>
  <body onload="initMap()">
    <h1>Map Init</h1>
    <!--The div element for the map -->
    <div id="map"></div> 

    
  </body>
  <script>
    
  </script>
</html>

Flask(betaa) - Copy (2)/webapp/templates/mapTest.html
<!DOCTYPE html>
            <html>
                <head>
                    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
                </head>
                <body onload="getLocation()">
                  {% for user in users %}
                  <span>{{user.user_name}}</span>
                  {% endfor %}
                    <h1>Using an iframe</h1>
                    <div id="map">{{ iframe|safe }}</span>

                     <span><a>Add your own markers</a></span>
                     <script>
                       /*function getPlaces() {
                        $.get('/places', (places) => {
                          var places = 
                        })
                       }*/

                    </script>
                </body>
               
            </html> 




Flask(betaa) - Copy (2)/webapp/templates/navbar.html
<nav> 
    <div id="home">
        <a href="{{url_for('web.mapView')}}" >View Map</a>
    </div>
</nav>

Flask(betaa) - Copy (2)/webapp/templates/userMap.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
     integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
     crossorigin=""/>
      <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
    integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
    crossorigin=""></script>
    <style>
      #map { height: 400px; }
  </style>
    <title>User map</title>
</head>
<body onload="showMarkers()">
  <!--div>
    <button onclick="showMarkers()">Show My Markers</button>
  </div-->
  <div id="map"></div>
  <script type="text/javascript">
  
    var mapDiv = document.getElementById('map');
    //init a map
    var map = L.map(mapDiv).setView([51.5074, -0.1278], 13);

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors',
    }).addTo(map);

    // Create a form popup
    var popup = L.popup();
    
    //onclick event handler function
    map.on('dblclick', function (e) {
      var lat = e.latlng.lat;
      var lon = e.latlng.lng;
      var popupText = 'Clicked location: Lat: ' + lat + ', Lon: ' + lon;
      popup
      .setLatLng(e.latlng)
      .setContent(`<form method="POST" action = "{{ url_for ('web.create_new_marker')}}"> 
        <span>Clicked location: Lat: ${lat}, Lon: ${lon}</span>
        <input type="text" name="title" id="title" placeholder="Name of the location"value="{{ request.form['title'] }}" ></input>
        <input type="text" name="text" id="text" placeholder="Description" value="{{ request.form['text']}}"> </input>
        <input type="hidden" id="lat" name="lat" value="${lat}">
        <input type="hidden" id="lon" name="lon" value="${lon}">
        <button type="submit">Create new marker</button>
        </form>`)
      .openOn(map);
    })  


    
    function showMarkers() {
      
      $.get('/usermarkers', (markers) => {
        var markersData = JSON.parse(markers)
        for (let i = 0; i<markersData.length; i++) {
           console.log(markersData[i].id)
           const title = markersData[i].title
           const text = markersData[i].text
           marker=L.marker([parseFloat(markersData[i].latitude), parseFloat(markersData[i].longitude)]).addTo(map)
          .bindPopup(`${title}, ${text} <button onclick="deleteMarker(${markersData[i].id})">Delete Marker</button>`)

        } 
      }) 
    } 

    function deleteMarker(marker_id) {
      $.get('/delete/' + marker_id , {
      }, (data) => {
        if (data=="True") {
          alert('Deleted')
          window.location.reload()
        } else {
          alert('Cannot delete, sorry')
          window.location.reload()


        }
      })
    } 

  
</script> 


<div class="dropdown">
  <select id="selectRegion" onchange="SelectRegion()">
  <div id="myDropdown" class="dropdown-content">
    <option value="Bac Giang">Bac Giang City</option>
    <option value="Ha Noi">Hanoi City</option>
  </div>
</div>

    
</body> 


</html>

Flask(betaa) - Copy (2)/webapp/templates/welcome.html
<p>Dang nhap duoc roi nha</p>
<a href = "{{  url_for('google.logout')  }}">Log Out</a>
<a href = "{{  url_for('web.getMap')  }}" >Bam Vao Con Di Nay</a>
<a href = "{{  url_for('web.user_map', user_id=current_user.id)  }}" >Bam Vao Con Di Nay</a>